version: "3.9"

services:
  asuntoservice:
    build: ./
    ports:
      - "5001:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=31.207.89.103;Port=5432;Database=SCGDS;Username=postgres;Password=asd123"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
